import type { FloorData, Material } from "../types";

export const vivitaFloor: FloorData = {
    id: "level-1",
    name: "VIVITA Level 1",
    elements: [
        {
            id: "window-wall",
            type: "outofbounds",
            x: 95,
            y: 92,
            width: 760,
            height: 56,
            name: "Window Wall",
            label: "Windows",
        },
        {
            id: "white-space",
            type: "compartment",
            x: 120,
            y: 175,
            width: 225,
            height: 260,
            name: "White Space",
            label: "White Space",
        },
        {
            id: "tinkering-studio",
            type: "compartment",
            x: 365,
            y: 175,
            width: 410,
            height: 305,
            name: "Tinkering Studio",
            label: "Open plan",
        },
        {
            id: "worktables",
            type: "table",
            x: 405,
            y: 290,
            width: 300,
            height: 155,
            name: "Work Tables",
            label: "Tables",
        },
        {
            id: "pegboard-storage",
            type: "workplace",
            x: 800,
            y: 165,
            width: 220,
            height: 305,
            name: "Pegboard Storage",
            label: "Pegboard wall",
        },
        {
            id: "vivi-shelving",
            type: "workplace",
            x: 805,
            y: 490,
            width: 210,
            height: 105,
            name: "VIVI Shelving",
            label: "Shelving",
        },
        {
            id: "stairs",
            type: "stairs",
            x: 1038,
            y: 245,
            width: 78,
            height: 250,
            name: "Stairs",
            label: "DN",
        },
        {
            id: "vivistudio",
            type: "compartment",
            x: 1128,
            y: 210,
            width: 170,
            height: 170,
            name: "VIVISTUDIO",
            label: "Photography",
        },
        {
            id: "roof-terrace",
            type: "outofbounds",
            x: 940,
            y: 75,
            width: 300,
            height: 120,
            name: "Roof Terrace",
            label: "Existing roof terrace",
        },
    ],
};

export const vivitaMaterials: Material[] = [
    {
        id: "mat-1",
        name: "HDMI Cable",
        description: "2m HDMI cable",
        quantity: 12,
        unit: "pcs",
        compartmentId: "white-space",
        createdAt: "2026-05-25T10:00:00Z",
    },
    {
        id: "mat-2",
        name: "Laptop",
        description: "Dell Latitude laptops",
        quantity: 6,
        unit: "units",
        compartmentId: "tinkering-studio",
        createdAt: "2026-05-25T10:10:00Z",
    },
    {
        id: "mat-3",
        name: "Craft Tools",
        description: "Shared tinkering tool sets",
        quantity: 18,
        unit: "sets",
        compartmentId: "worktables",
        createdAt: "2026-05-25T10:20:00Z",
    },
    {
        id: "mat-4",
        name: "Pegboard Parts",
        description: "Connectors, fasteners, and display samples",
        quantity: 42,
        unit: "pcs",
        compartmentId: "pegboard-storage",
        createdAt: "2026-05-25T10:25:00Z",
    },
    {
        id: "mat-5",
        name: "Ethernet Cable",
        description: "Cat 6 networking cable",
        quantity: 25,
        unit: "pcs",
        compartmentId: "vivi-shelving",
        createdAt: "2026-05-25T10:20:00Z",
    },
    {
        id: "mat-6",
        name: "Projector",
        description: "Portable presentation projector",
        quantity: 1,
        unit: "unit",
        compartmentId: "white-space",
        createdAt: "2026-05-25T10:30:00Z",
    },
    {
        id: "mat-7",
        name: "Camera Tripod",
        description: "Photography studio tripod",
        quantity: 3,
        unit: "pcs",
        compartmentId: "vivistudio",
        createdAt: "2026-05-25T10:40:00Z",
    },
];
